# Generated by Django 3.1 on 2021-08-31 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=200, verbose_name='publicId из личного кабинета CP')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=200, verbose_name='Номер заказа')),
                ('transaction_id', models.CharField(blank=True, default='', max_length=200, verbose_name='Номер транзакции')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Сумма платежа')),
                ('status', models.CharField(choices=[('AwaitingAuthentication', 'Ожидает аутентификации'), ('Authorized', 'Авторизована'), ('Completed', 'Завершена'), ('Cancelled', 'Отменена'), ('Declined', 'Отклонена')], default='AwaitingAuthentication', max_length=100, verbose_name='Статус')),
                ('is_test', models.BooleanField(default=False, verbose_name='Тестовый платеж')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
