# Generated by Django 3.1 on 2021-09-02 13:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_cloudpayments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_uuid',
            field=models.CharField(default=uuid.uuid4, max_length=64, verbose_name='UUID'),
        ),
    ]
