# Generated by Django 3.1 on 2021-09-02 14:01

from django.db import migrations, models
import garpix_cloudpayments.models.payment


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_cloudpayments', '0002_payment_payment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_uuid',
            field=models.CharField(default=garpix_cloudpayments.models.payment.generate_uuid, max_length=64, verbose_name='UUID'),
        ),
    ]
