# Generated by Django 3.1 on 2023-02-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_cloudpayments', '0003_auto_20210902_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='password_api',
            field=models.CharField(default='', max_length=200, verbose_name='Пароль для API из личного кабинета CP'),
        ),
    ]
