# Generated by Django 3.1 on 2023-02-06 10:16

from django.db import migrations, models
import garpix_menu.validators
import garpix_page.utils.all_sites
import garpix_utils.file.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('garpix_menu', '0002_auto_20210901_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=garpix_utils.file.file_field.get_file_path, verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='hash',
            field=models.CharField(blank=True, default='', help_text='Если хотите дать ссылку на конкретный элемент страницы. Например - #example', max_length=256, verbose_name='Якорь'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=garpix_utils.file.file_field.get_file_path, validators=[garpix_menu.validators.validate_type, garpix_menu.validators.validate_size], verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='sites',
            field=models.ManyToManyField(default=garpix_page.utils.all_sites.get_all_sites, to='sites.Site', verbose_name='Сайты для отображения'),
        ),
    ]
