# Generated by Django 3.1 on 2023-02-06 10:16

from django.db import migrations, models
import django.db.models.deletion
import garpix_page.fields.grapes_js_html
import garpix_page.mixins.models.clone_mixin
import garpix_page.utils.all_sites
import garpix_utils.file.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sites', '0002_alter_domain_unique'),
        ('garpix_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Включено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('text_title', models.CharField(blank=True, default='', max_length=128, verbose_name='Заголовок')),
                ('text_title_ru', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Компонент',
                'verbose_name_plural': 'Компоненты',
                'ordering': ('created_at', 'title'),
            },
            bases=(garpix_page.mixins.models.clone_mixin.CloneMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='basepage',
            name='sites',
            field=models.ManyToManyField(default=garpix_page.utils.all_sites.get_all_sites, to='sites.Site', verbose_name='Сайты для отображения'),
        ),
        migrations.CreateModel(
            name='GrapesJsHtmlComponent',
            fields=[
                ('basecomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basecomponent')),
                ('html', garpix_page.fields.grapes_js_html.GrapesJsHtmlField()),
            ],
            options={
                'verbose_name': 'GrapesJs компонент',
                'verbose_name_plural': 'GrapesJs компоненты',
            },
            bases=('garpix_page.basecomponent',),
        ),
        migrations.CreateModel(
            name='SeoTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Включено')),
                ('rule_field', models.CharField(max_length=255, verbose_name='Поле')),
                ('model_rule_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('rule_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение')),
                ('seo_title', models.CharField(blank=True, default='', max_length=250, verbose_name='SEO заголовок страницы (title)')),
                ('seo_title_ru', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='SEO заголовок страницы (title)')),
                ('seo_keywords', models.CharField(blank=True, default='', max_length=250, verbose_name='SEO ключевые слова (keywords)')),
                ('seo_keywords_ru', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='SEO ключевые слова (keywords)')),
                ('seo_description', models.TextField(blank=True, default='', verbose_name='SEO описание (description)')),
                ('seo_description_ru', models.TextField(blank=True, default='', null=True, verbose_name='SEO описание (description)')),
                ('seo_author', models.CharField(blank=True, default='', max_length=250, verbose_name='SEO автор (author)')),
                ('seo_author_ru', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='SEO автор (author)')),
                ('seo_og_type', models.CharField(blank=True, default='website', max_length=250, verbose_name='SEO og:type')),
                ('seo_image', models.FileField(blank=True, null=True, upload_to=garpix_utils.file.file_field.get_file_path, verbose_name='SEO изображение')),
                ('priority_order', models.PositiveIntegerField(default=1, help_text='Чем меньше число, тем выше приоритет', verbose_name='Приоритетность применения')),
                ('sites', models.ManyToManyField(default=garpix_page.utils.all_sites.get_all_sites, to='sites.Site', verbose_name='Сайты для применения')),
            ],
            options={
                'verbose_name': 'Шаблон для seo',
                'verbose_name_plural': 'Шаблоны для seo',
                'ordering': ['priority_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PageComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_order', models.IntegerField(default=1, verbose_name='Порядок отображения')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garpix_page.basecomponent', verbose_name='Компонент')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garpix_page.basepage', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Компонент страницы',
                'verbose_name_plural': 'Компоненты страницы',
                'ordering': ('view_order',),
                'unique_together': {('component', 'page')},
            },
        ),
        migrations.CreateModel(
            name='GarpixPageSiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robots_txt', models.TextField(default='User-agent: *\nDisallow: /admin/\nDisallow: /api/', verbose_name='Содержимое файла robots.txt')),
                ('sitemap_frequency', models.CharField(choices=[('always', 'always'), ('hourly', 'hourly'), ('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly'), ('never', 'never')], default='always', max_length=7, verbose_name='Sitemap changefreq')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.AddField(
            model_name='basecomponent',
            name='pages',
            field=models.ManyToManyField(blank=True, related_name='components', through='garpix_page.PageComponent', to='garpix_page.BasePage', verbose_name='Страницы для отображения'),
        ),
        migrations.AddField(
            model_name='basecomponent',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_garpix_page.basecomponent_set+', to='contenttypes.contenttype'),
        ),
    ]
